"""
compare.py — turn the per-machine benchmark JSONs into the COOL evidence table (+ optional chart).

Reads ``runs/bench/<label>__<workload>.json`` files written by ``product_bench.py`` and writes
``docs/cool_benchmark.md``: one row per run (architecture, OpenCV provenance — COOL only when
``cv2`` was loaded from ``/opt/cool`` —, threads, p50/p95 per stage, throughput, $/1k frames,
survey-hour compute + cost), then the two comparisons the award asks for:

* **(B) → (C)** Graviton stock OpenCV → Graviton COOL, same instance: COOL's own contribution;
* **(A) → (C)** x86 → Graviton + COOL: the headline latency *and* cost-per-survey-hour story.

    python -m src.bench.compare [--dir runs/bench] [--chart docs/img/cool_benchmark.png]
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ORDER = ("baseline_x86", "graviton_stock", "graviton_cool")


def load(d: Path) -> list[dict]:
    runs = [json.loads(p.read_text()) for p in sorted(d.glob("*__*.json"))]
    return sorted(runs, key=lambda r: (r["workload"], ORDER.index(r["label"]) if r["label"] in ORDER else 9, r["label"]))


def _row(r: dict) -> str:
    fp, st, c = r["fingerprint"], r["stages_ms"], r["cost"]
    ec2 = fp.get("ec2") or {}
    where = ec2.get("instance-type") or fp["host"].get("cpu_model", "")[:28]
    ocv = f"{fp['opencv']['version']} {'**COOL**' if fp['opencv']['is_cool_path'] else 'stock'}"
    stage = " · ".join(f"{k} {v['p50']:.0f}" for k, v in st.items() if k not in ("total",))
    sh = c["survey_hour"]
    usd1k = f"${c['usd_per_1k_frames']:.4f}" if c.get("usd_per_1k_frames") is not None else "—"
    ush = f"${sh['usd']:.5f}" if sh.get("usd") is not None else "—"
    return (f"| `{r['label']}` | {r['workload']} | {fp['host']['machine']} · {where} | {ocv} | {r['runtime']['threads']} "
            f"| **{st['total']['p50']:.1f}** / {st['total']['p95']:.1f} | {stage} | {r['throughput_fps']} "
            f"| {usd1k} | {sh['compute_s']:.1f} s · RTF {sh['real_time_factor']:.4f} · {ush} |")


def _ratio(a: dict, b: dict, key: str = "p50") -> str:
    x, y = a["stages_ms"]["total"][key], b["stages_ms"]["total"][key]
    return f"{x / y:.2f}×" if y else "—"


def report(runs: list[dict]) -> str:
    L = ["# COOL benchmark — the DEPTH product workload, per stage",
         "",
         "_Generated by `python -m src.bench.compare` from `runs/bench/*.json` (`python -m src.bench.product_bench`)._",
         "",
         "Workload `product` = exactly what `/api/analyze` runs per frame: JPEG decode → Stage 1 "
         "(canonicalise + bottom track) → YOLO11 via `cv2.dnn` → evidence + guaranteed tiers → overlay + JPEG "
         "encode. `cv` = the same minus the network (the OpenCV image-processing share, incl. `cv2.remap` and "
         "range gain). A run counts as **COOL** only if `cv2.__file__` is under `/opt/cool` (provenance, not "
         "\"KleidiCV in the build\", which the stock Arm wheel also reports).",
         "",
         "| run | workload | host | OpenCV | threads | total ms p50 / p95 | per stage p50 (ms) | fps | $ / 1k frames | survey-hour: compute · real-time factor · $ |",
         "|---|---|---|---|--:|--:|---|--:|--:|---|"]
    L += [_row(r) for r in runs]
    by = {(r["label"], r["workload"]): r for r in runs}
    cmp = []
    for wl in sorted({r["workload"] for r in runs}):
        a, b, c = by.get(("baseline_x86", wl)), by.get(("graviton_stock", wl)), by.get(("graviton_cool", wl))
        if b and c:
            cmp.append(f"| {wl} | **COOL on identical Graviton** (B → C) | {_ratio(b, c)} faster p50 · {_ratio(b, c, 'p95')} p95 |")
        if a and c:
            ca, cc = a["cost"]["survey_hour"].get("usd"), c["cost"]["survey_hour"].get("usd")
            cost = f" · {ca / cc:.2f}× cheaper per survey-hour" if ca and cc else ""
            cmp.append(f"| {wl} | **x86 → Graviton + COOL** (A → C) | {_ratio(a, c)} faster p50{cost} |")
    if cmp:
        L += ["", "| workload | comparison | result |", "|---|---|---|"] + cmp
    else:
        L += ["", "_A/B/C comparison appears once the EC2 runs (`infra/bench_cool.sh`) are in `runs/bench/`._"]
    L += ["", "**Survey-hour model:** frames per survey-hour = ping rate × 3600 / pings per frame × channels "
          "(assumptions recorded in each JSON; default 15 Hz, 640 pings/frame, port + starboard). "
          "Real-time factor = compute seconds per hour of sonar ÷ 3600 (< 1 ⇒ keeps up with the boat).",
          "", "---", "_Numbers in this file are regenerated by the script; do not edit by hand._", ""]
    return "\n".join(L)


def chart(runs: list[dict], out: Path) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed - chart skipped")
        return
    prod = [r for r in runs if r["workload"] == "product"] or runs
    stages = [k for k in prod[0]["stages_ms"] if k != "total"]
    # validated categorical slots (dataviz reference palette, light mode; the table in the report is
    # the relief for the three sub-3:1 slots). Stacked MEANS — means add up, p50s do not.
    colors = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4"]
    ink, ink2, surface = "#0b0b0b", "#52514e", "#fcfcfb"
    fig, ax = plt.subplots(figsize=(7.5, 1.1 + 0.55 * len(prod)), facecolor=surface)
    ax.set_facecolor(surface)
    for i, r in enumerate(prod):
        left = 0.0
        for j, k in enumerate(stages):
            v = r["stages_ms"][k]["mean"]
            ax.barh(i, v, left=left, color=colors[j % len(colors)], label=k if i == 0 else None, height=0.56,
                    edgecolor=surface, linewidth=2)
            left += v
        ax.text(left + 4, i, f"{r['stages_ms']['total']['mean']:.0f} ms", va="center", fontsize=8, color=ink)
    ax.set_yticks(range(len(prod)), [r["label"] for r in prod], fontsize=8, color=ink)
    ax.invert_yaxis()
    ax.set_xlabel("mean latency per frame (ms), stacked by stage", color=ink2, fontsize=8)
    ax.tick_params(colors=ink2, labelsize=8)
    ax.grid(axis="x", color="#e4e3df", linewidth=0.6); ax.set_axisbelow(True)
    ax.spines[["top", "right", "left"]].set_visible(False); ax.spines["bottom"].set_color("#c9c8c2")
    leg = ax.legend(ncol=len(stages), fontsize=7, frameon=False, loc="lower center", bbox_to_anchor=(0.5, 1.0))
    for t in leg.get_texts():
        t.set_color(ink2)
    out.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout(); fig.savefig(out, dpi=160, facecolor=surface); plt.close(fig)
    print(f"chart -> {out}")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--dir", default=str(REPO / "runs" / "bench"))
    ap.add_argument("--out", default=str(REPO / "docs" / "cool_benchmark.md"))
    ap.add_argument("--chart", default=str(REPO / "docs" / "img" / "cool_benchmark.png"))
    a = ap.parse_args()
    runs = load(Path(a.dir))
    if not runs:
        raise SystemExit(f"no benchmark JSONs in {a.dir}")
    Path(a.out).write_text(report(runs), encoding="utf-8")
    print(f"report -> {a.out} ({len(runs)} runs)")
    if a.chart:
        chart(runs, Path(a.chart))


if __name__ == "__main__":
    main()
